"""Add file fields to reports table

Revision ID: 18bba4a05125
Revises: 0a5da85da906
Create Date: 2025-08-24 19:16:13.856551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bba4a05125'
down_revision = '0a5da85da906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True, comment='原始文件名'))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True, comment='服务器存储路径'))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'))
        batch_op.add_column(sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件扩展名'))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='提交时间'))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
