"""修复迁移

Revision ID: 3d01a4b2db31
Revises: 
Create Date: 2025-09-03 11:20:26.525553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d01a4b2db31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_contents')
    op.drop_table('video_watch_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_watch_history',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('video_id', sa.INTEGER(), nullable=False),
    sa.Column('watched_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('watch_duration', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['course_contents.content_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_contents',
    sa.Column('content_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('class_id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    # ### end Alembic commands ###
